baseURL = 'https://quaran.org/'
languageCode = 'en-US'
title = 'Quran Study'
theme = 'book'

[menus]
  [[menus.main]]
    name = 'Articles'
    pageRef = '/articles'
    weight = 20

  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 30

[module]
  [module.hugoVersion]
    min = '0.147.0'
