baseURL = 'https://quaran.org/'
title = 'Quran Study'

# Language & SEO
languageCode = 'en-US'
defaultContentLanguage = "en"
enableRobotsTXT = true
pluralizeListTitles = false
printPathWarnings = true
uglyURLs = false

ignoreFiles = [
  "/content/quran/([2-9]|[1-9][0-9]|100)/.*",
  "/content/notes/.*"
]

[taxonomies]
  tag = 'tags'
  surah = 'surah'

[menus]
  [[menus.main]]
    name = 'Quran'
    pageRef = '/quran'
    weight = 10
  [[menus.main]]
    name = 'Surah'
    pageRef = '/surah'
    weight = 20
  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 30
  [[menus.main]]
    name = 'Salah'
    pageRef = '/salah'
    weight = 40

[module]
  [module.hugoVersion]
    min = '0.147.0'
